# Primer workflow
name: My First Workflow
on: 
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  first_job:  
    name: Mi primer job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hola Mundo from ${{ github.actor }}"
      
      
        
      
      
