# Segundo workflow
name: My First Workflow
on: 
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  primer_job:  
    name: Saluda al usuario
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hola Mundo from ${{ github.actor }}"
  segundo_job:  
    name: Ejecuta el tree
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - run: tree          
