# Primer workflow
name: My First Workflow
on: 
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  first_job:  
    name: Mi primer job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - run: tree
      
      
      
        
      
      
