# Primer workflow
name: My First Workflow
on: 
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  first_job:  
    name: Muestra el tree
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - shell: bash
      - run: tree
        
