# Segundo workflow
name: My First Workflow
on: 
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  first_job:  
    name: Saluda al usuario
    runs-on: ubuntu-latest
    steps:
      - name: Saludando...
      - run: echo "Hola Mundo from ${{ github.actor }}"
      - uses: actions/checkout@v4.1.6
      - run: tree      
