# Segundo workflow
name: My Second Workflow
on: 
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  first_job:  
    name: Saluda al usuario
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hola Mundo from ${{ github.actor }}"
