# Primer workflow
name: My Second Workflow
on: 
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  first_job:  
    name: Saluda al usuario
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - run: tree
